[editor]
indent-guides.render = true
line-number = "relative"
statusline.right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]

[keys.normal]
backspace = ":write"
esc = ":write"
C-n = ":new"
C-space = ":write"

[keys.normal.ret]
i = ":toggle indent-guides.render"
l = ":toggle line-number absolute relative"
s = ":toggle whitespace.render all none"
w = ":toggle soft-wrap.enable"

[keys.insert]
C-space = "normal_mode"
